"use client";

import type { GeneratedContentWithRelations } from "@socialcreator/types/agent";
import { formatDateTime } from "@socialcreator/utils";
import { Check, Clock, Eye, Send, X } from "lucide-react";
import Link from "next/link";
import { useContentStore, useUIStore } from "@/lib/stores";
import { ContentStatusBadge } from "./content-status-badge";
import { PlatformBadge } from "./platform-badge";

interface ContentCardProps {
  content: GeneratedContentWithRelations;
  profileId?: string;
  onApprove?: (id: string) => void;
  onReject?: (id: string) => void;
  onPublish?: (id: string) => void;
}

export function ContentCard({
  content: propContent,
  onApprove: propOnApprove,
  onReject: propOnReject,
  onPublish: propOnPublish,
}: ContentCardProps) {
  // Prefer Zustand store over props
  const storeItem = useContentStore((s) => s.items.find((i) => i.id === propContent.id));
  const storeUpdateItem = useContentStore((s) => s.updateItem);
  const storeSelectItem = useContentStore((s) => s.selectItem);
  const openModal = useUIStore((s) => s.openModal);

  const content = storeItem ?? propContent;
  const onApprove =
    propOnApprove ?? ((id: string) => storeUpdateItem(id, { status: "APPROVED" as any }));
  const onReject =
    propOnReject ?? ((id: string) => storeUpdateItem(id, { status: "REJECTED" as any }));
  const onPublish =
    propOnPublish ??
    ((id: string) => {
      storeSelectItem(id);
      openModal("publish", { contentId: id });
    });

  const isDraft = content.status === "DRAFT";
  const isApproved = content.status === "APPROVED";
  const isScheduled = content.status === "SCHEDULED";

  return (
    <div className="group bg-surface-card border border-hairline rounded-xl p-5 hover:shadow-card-hover transition-all">
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-2">
          <PlatformBadge platform={content.platform} size="sm" />
          <ContentStatusBadge status={content.status} />
          {isScheduled && <Clock className="w-3.5 h-3.5 text-blue-600" />}
        </div>
        <span className="text-caption text-muted">{formatDateTime(content.createdAt)}</span>
      </div>

      {/* Content Preview */}
      <p className="text-body-sm text-body line-clamp-3 mb-3">{content.textContent}</p>

      {/* Hashtags */}
      {content.hashtags.length > 0 && (
        <div className="flex flex-wrap gap-1 mb-4">
          {content.hashtags.slice(0, 5).map((tag) => (
            <span key={tag} className="text-caption text-muted">
              #{tag}
            </span>
          ))}
          {content.hashtags.length > 5 && (
            <span className="text-caption text-muted-soft">+{content.hashtags.length - 5}</span>
          )}
        </div>
      )}

      {/* Source */}
      {content.run?.agent && (
        <p className="text-caption text-muted mb-4">Generated by {content.run.agent.name}</p>
      )}

      {/* Actions */}
      <div className="flex items-center gap-2 pt-3 border-t border-hairline">
        <Link
          href={`/content/${content.id}`}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption text-muted hover:bg-surface-strong transition-colors"
        >
          <Eye className="w-3.5 h-3.5" />
          View
        </Link>

        {isDraft && (
          <>
            <button
              type="button"
              onClick={() => onApprove?.(content.id)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption bg-semantic-success/10 text-semantic-success hover:bg-semantic-success/20 transition-colors"
            >
              <Check className="w-3.5 h-3.5" />
              Approve
            </button>
            <button
              type="button"
              onClick={() => onReject?.(content.id)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption bg-semantic-error/10 text-semantic-error hover:bg-semantic-error/20 transition-colors"
            >
              <X className="w-3.5 h-3.5" />
              Reject
            </button>
          </>
        )}

        {isApproved && onPublish && (
          <button
            type="button"
            onClick={() => onPublish?.(content.id)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption bg-primary text-on-primary hover:bg-primary-active transition-colors"
          >
            <Send className="w-3.5 h-3.5" />
            Publish
          </button>
        )}

        {isScheduled && content.scheduledPublishAt && (
          <div className="flex items-center gap-1.5 text-caption text-blue-600 ml-auto">
            <Clock className="w-3.5 h-3.5" />
            Scheduled for {formatDateTime(content.scheduledPublishAt)}
          </div>
        )}
      </div>
    </div>
  );
}
