"use client";

import { useState } from "react";
import { X, Check, AlertTriangle } from "lucide-react";
import { cn } from "@/lib/utils";
import { PlatformBadge } from "./platform-badge";
import { ContentStatusBadge } from "./content-status-badge";
import type { GeneratedContentWithRelations } from "@/types/agent";

interface ApprovalPanelProps {
  content: GeneratedContentWithRelations | null;
  isOpen: boolean;
  onClose: () => void;
  onApprove: (id: string) => void;
  onReject: (id: string, reason?: string) => void;
  isLoading?: boolean;
}

export function ApprovalPanel({
  content,
  isOpen,
  onClose,
  onApprove,
  onReject,
  isLoading,
}: ApprovalPanelProps) {
  const [rejectReason, setRejectReason] = useState("");
  const [showRejectInput, setShowRejectInput] = useState(false);

  if (!isOpen || !content) return null;

  const handleReject = () => {
    if (showRejectInput) {
      onReject(content.id, rejectReason);
      setShowRejectInput(false);
      setRejectReason("");
    } else {
      setShowRejectInput(true);
    }
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/30 z-40"
        onClick={onClose}
      />

      {/* Panel */}
      <div className="fixed right-0 top-0 h-screen w-full max-w-lg bg-surface-dark z-50 shadow-xl overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-title-md text-on-dark">Review Content</h2>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-surface-dark-elevated text-on-dark-soft hover:text-on-dark transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Content Info */}
          <div className="mb-6">
            <div className="flex items-center gap-3 mb-4">
              <PlatformBadge platform={content.platform} />
              <ContentStatusBadge status={content.status} />
            </div>

            {content.run?.agent && (
              <p className="text-body-sm text-on-dark-soft mb-4">
                Generated by <span className="text-on-dark">{content.run.agent.name}</span>
              </p>
            )}
          </div>

          {/* Full Content */}
          <div className="bg-surface-dark-elevated rounded-xl p-6 mb-6">
            <h3 className="text-body-strong text-on-dark mb-3">Content</h3>
            <p className="text-body-sm text-on-dark-soft whitespace-pre-wrap">
              {content.textContent}
            </p>

            {content.hashtags.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-hairline">
                {content.hashtags.map((tag) => (
                  <span
                    key={tag}
                    className="px-2 py-1 rounded bg-surface-dark text-caption text-on-dark-soft"
                  >
                    #{tag}
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Character Count */}
          <div className="mb-6">
            <p className="text-caption text-on-dark-soft">
              {content.textContent.length} characters
            </p>
          </div>

          {/* Reject Reason Input */}
          {showRejectInput && (
            <div className="mb-6">
              <label className="block text-body-sm text-on-dark mb-2">
                Reason for rejection (optional)
              </label>
              <textarea
                value={rejectReason}
                onChange={(e) => setRejectReason(e.target.value)}
                placeholder="Enter reason..."
                className="w-full px-4 py-3 rounded-lg bg-surface-dark-elevated border border-hairline text-body-md text-on-dark placeholder:text-muted-soft focus:outline-none focus:border-primary resize-none"
                rows={3}
              />
            </div>
          )}

          {/* Actions */}
          <div className="flex items-center gap-3">
            <button
              onClick={handleReject}
              disabled={isLoading}
              className={cn(
                "flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-pill transition-colors",
                showRejectInput
                  ? "bg-semantic-error text-white hover:bg-semantic-error/90"
                  : "bg-surface-dark-elevated text-semantic-error hover:bg-semantic-error/10"
              )}
            >
              <AlertTriangle className="w-4 h-4" />
              {showRejectInput ? "Confirm Reject" : "Reject"}
            </button>
            <button
              onClick={() => onApprove(content.id)}
              disabled={isLoading}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-pill bg-semantic-success text-white hover:bg-semantic-success/90 transition-colors disabled:opacity-50"
            >
              <Check className="w-4 h-4" />
              Approve
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
