"use client";

import Link from "next/link";
import { Eye, Check, X, Send } from "lucide-react";
import { cn } from "@/lib/utils";
import { PlatformBadge } from "./platform-badge";
import { ContentStatusBadge } from "./content-status-badge";
import type { GeneratedContentWithRelations } from "@/types/agent";
import { formatDateTime } from "@/lib/utils";

interface ContentCardProps {
  content: GeneratedContentWithRelations;
  profileId?: string;
  onApprove?: (id: string) => void;
  onReject?: (id: string) => void;
  onPublish?: (id: string) => void;
}

export function ContentCard({ content, profileId, onApprove, onReject, onPublish }: ContentCardProps) {
  const isDraft = content.status === "DRAFT";
  const isApproved = content.status === "APPROVED";

  return (
    <div className="group bg-surface-card border border-hairline rounded-xl p-5 hover:shadow-card-hover transition-all">
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-2">
          <PlatformBadge platform={content.platform} size="sm" />
          <ContentStatusBadge status={content.status} />
        </div>
        <span className="text-caption text-muted">{formatDateTime(content.createdAt)}</span>
      </div>

      {/* Content Preview */}
      <p className="text-body-sm text-body line-clamp-3 mb-3">{content.textContent}</p>

      {/* Hashtags */}
      {content.hashtags.length > 0 && (
        <div className="flex flex-wrap gap-1 mb-4">
          {content.hashtags.slice(0, 5).map((tag) => (
            <span key={tag} className="text-caption text-muted">
              #{tag}
            </span>
          ))}
          {content.hashtags.length > 5 && (
            <span className="text-caption text-muted-soft">+{content.hashtags.length - 5}</span>
          )}
        </div>
      )}

      {/* Source */}
      {content.run?.agent && (
        <p className="text-caption text-muted mb-4">
          Generated by {content.run.agent.name}
        </p>
      )}

      {/* Actions */}
      <div className="flex items-center gap-2 pt-3 border-t border-hairline">
        <Link
          href={`/content/${content.id}`}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption text-muted hover:bg-surface-strong transition-colors"
        >
          <Eye className="w-3.5 h-3.5" />
          View
        </Link>

        {isDraft && (
          <>
            <button
              onClick={() => onApprove?.(content.id)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption bg-semantic-success/10 text-semantic-success hover:bg-semantic-success/20 transition-colors"
            >
              <Check className="w-3.5 h-3.5" />
              Approve
            </button>
            <button
              onClick={() => onReject?.(content.id)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption bg-semantic-error/10 text-semantic-error hover:bg-semantic-error/20 transition-colors"
            >
              <X className="w-3.5 h-3.5" />
              Reject
            </button>
          </>
        )}

        {isApproved && onPublish && (
          <button
            onClick={() => onPublish?.(content.id)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-caption bg-primary text-on-primary hover:bg-primary-active transition-colors"
          >
            <Send className="w-3.5 h-3.5" />
            Publish
          </button>
        )}
      </div>
    </div>
  );
}
