/**
 * Tests for ContentCard component.
 *
 * Tests rendering of content text, platform badge, status-specific actions,
 * hashtags with overflow, generated-by attribution, view link, and callbacks.
 */

import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { createContent } from "@/components/__tests__/test-fixtures";
import { render, screen } from "@/components/__tests__/test-utils";
import { ContentCard } from "../content-card";

// ── Hoisted mocks ────────────────────────────────────────────────────────

const mockPlatforms = vi.hoisted(() => [
  { value: "X", label: "X (Twitter)", icon: "𝕏" },
  { value: "INSTAGRAM", label: "Instagram", icon: "📷" },
  { value: "LINKEDIN", label: "LinkedIn", icon: "💼" },
]);

const mockStatusLabels = vi.hoisted(() => ({
  DRAFT: "Draft",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  SCHEDULED: "Scheduled",
  PUBLISHED: "Published",
  FAILED: "Failed",
}));

const mockStatusColors = vi.hoisted(() => ({
  DRAFT: "bg-gray-100 text-gray-700",
  APPROVED: "bg-green-100 text-green-700",
  REJECTED: "bg-red-100 text-red-700",
  SCHEDULED: "bg-blue-100 text-blue-700",
  PUBLISHED: "bg-purple-100 text-purple-700",
  FAILED: "bg-red-100 text-red-700",
}));

const mockContentStore = vi.hoisted(() => ({
  items: [],
  updateItem: vi.fn(),
  selectItem: vi.fn(),
  fetchItems: vi.fn(),
}));

const mockUIStore = vi.hoisted(() => ({
  openModal: vi.fn(),
}));

// ── Module mocks ─────────────────────────────────────────────────────────

vi.mock("@/lib/stores", () => ({
  useContentStore: (selector: any) => selector(mockContentStore),
  useUIStore: (selector: any) => selector(mockUIStore),
}));

vi.mock("@socialcreator/utils", () => ({
  formatDateTime: vi.fn(() => "Jun 1, 2025"),
  cn: (...args: any[]) => args.filter(Boolean).join(" "),
}));

vi.mock("@socialcreator/types/profile", () => ({
  PLATFORMS: mockPlatforms,
  CONTENT_STATUS_LABELS: mockStatusLabels,
  CONTENT_STATUS_COLORS: mockStatusColors,
}));

vi.mock("lucide-react", () => ({
  Check: "svg-check",
  Clock: "svg-clock",
  Eye: "svg-eye",
  Send: "svg-send",
  X: "svg-x",
}));

vi.mock("next/link", () => ({
  default: ({ children, href, ...props }: any) => (
    <a href={href} {...props}>
      {children}
    </a>
  ),
}));

// ── Tests ────────────────────────────────────────────────────────────────

describe("ContentCard", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("renders content text and platform badge", () => {
    const content = createContent();
    render(<ContentCard content={content} />);

    expect(screen.getByText(content.textContent)).toBeInTheDocument();
    expect(screen.getByText("X (Twitter)")).toBeInTheDocument();
  });

  it("shows approve and reject buttons for DRAFT status", () => {
    const content = createContent();
    render(<ContentCard content={content} />);

    expect(screen.getByText("Approve")).toBeInTheDocument();
    expect(screen.getByText("Reject")).toBeInTheDocument();
  });

  it("shows publish button for APPROVED status", () => {
    const content = createContent({ id: "content-2", status: "APPROVED" });
    render(<ContentCard content={content} />);

    expect(screen.getByText("Publish")).toBeInTheDocument();
    expect(screen.queryByText("Approve")).not.toBeInTheDocument();
    expect(screen.queryByText("Reject")).not.toBeInTheDocument();
  });

  it("shows scheduled info for SCHEDULED status", () => {
    const content = createContent({
      id: "content-3",
      status: "SCHEDULED",
      scheduledPublishAt: new Date("2025-06-15T14:00:00Z"),
    });
    render(<ContentCard content={content} />);

    expect(screen.getByText(/Scheduled for/)).toBeInTheDocument();
    expect(screen.getByText("Jun 1, 2025")).toBeInTheDocument();
  });

  it('shows "Generated by" when content has run.agent', () => {
    const content = createContent({
      run: { id: "run-1", agent: { id: "agent-1", name: "Test Agent" } },
    });
    render(<ContentCard content={content} />);

    expect(screen.getByText(/Generated by Test Agent/)).toBeInTheDocument();
  });

  it("renders hashtags with # prefix", () => {
    const content = createContent({ hashtags: ["test", "social"] });
    render(<ContentCard content={content} />);

    expect(screen.getByText("#test")).toBeInTheDocument();
    expect(screen.getByText("#social")).toBeInTheDocument();
  });

  it("shows +N overflow when more than 5 hashtags", () => {
    const content = createContent({
      hashtags: ["a", "b", "c", "d", "e", "f", "g"],
    });
    render(<ContentCard content={content} />);
    // 7 - 5 = 2 overflow
    expect(screen.getByText("+2")).toBeInTheDocument();
  });

  it("does not show +N when 5 or fewer hashtags", () => {
    const content = createContent({
      hashtags: ["a", "b", "c"],
    });
    render(<ContentCard content={content} />);
    expect(screen.queryByText(/^\+/)).not.toBeInTheDocument();
  });

  it("renders view link navigating to /content/{id}", () => {
    const content = createContent();
    render(<ContentCard content={content} />);

    const viewLink = screen.getByText("View");
    expect(viewLink.closest("a")).toHaveAttribute("href", "/content/content-1");
  });

  it("calls onApprove when approve button is clicked", async () => {
    const user = userEvent.setup();
    const onApprove = vi.fn();
    const content = createContent();

    render(<ContentCard content={content} onApprove={onApprove} />);

    await user.click(screen.getByText("Approve"));
    expect(onApprove).toHaveBeenCalledWith("content-1");
  });

  it("calls onReject when reject button is clicked", async () => {
    const user = userEvent.setup();
    const onReject = vi.fn();
    const content = createContent();

    render(<ContentCard content={content} onReject={onReject} />);

    await user.click(screen.getByText("Reject"));
    expect(onReject).toHaveBeenCalledWith("content-1");
  });

  it("calls onPublish when publish button is clicked on approved content", async () => {
    const user = userEvent.setup();
    const onPublish = vi.fn();
    const content = createContent({ id: "content-2", status: "APPROVED" });

    render(<ContentCard content={content} onPublish={onPublish} />);

    await user.click(screen.getByText("Publish"));
    expect(onPublish).toHaveBeenCalledWith("content-2");
  });

  it("renders status badge showing current status", () => {
    const content = createContent();
    render(<ContentCard content={content} />);

    expect(screen.getByText("Draft")).toBeInTheDocument();
  });

  it("renders Clock icon for SCHEDULED status", () => {
    const content = createContent({
      id: "content-3",
      status: "SCHEDULED",
      scheduledPublishAt: new Date("2025-06-15T14:00:00Z"),
    });
    const { container } = render(<ContentCard content={content} />);

    expect(container.innerHTML).toContain("svg-clock");
  });

  it("does not show action buttons when no callbacks provided for DRAFT", () => {
    const content = createContent();
    render(<ContentCard content={content} />);

    // Without explicit onApprove/onReject, the component uses store defaults.
    // Approve/Reject should still render because isDraft is true.
    expect(screen.getByText("Approve")).toBeInTheDocument();
    expect(screen.getByText("Reject")).toBeInTheDocument();
  });

  it("does not show publish button when onPublish is undefined for APPROVED", () => {
    // The component checks `isApproved && onPublish && (...)`
    // If onPublish is not provided, the fallback is set, so publish should show
    const content = createContent({ id: "content-2", status: "APPROVED" });
    render(<ContentCard content={content} />);

    // The fallback onPublish uses store: storeSelectItem + openModal("publish")
    // So the button should still be rendered
    expect(screen.getByText("Publish")).toBeInTheDocument();
  });
});
